### ISSUE TITLE
Missing Gene annotations and De novo motifs

### ISSUE THREAD

**Issue by RM83** [mbassalbioinformatics/ChIP-AP#2]
Hi,
I run ChIP-AP on your given data set (SALL4; GSE172355) using the following command. I am not getting gene annotations (Entrez id, gene name, gene description, etc.) in the output file [setname]_all_peaks_annotated.tsv. I used the default settings table. Please suggest what I am missing here.

[xxx]$ ./chipap.py --mode single --ref hg38 --genome PATH/genomes --output PATH/output --setname xxx --sample_table PATH/xxx_samp_table.txt --custom_setting_table PATH/chip_ap_default_seetings_table.txt --fcmerge --goann --pathann --deltemp --thread 24 --run

Also, the following two files were not generated. 
Output  : 24_homer_motif_enrichment / ... / homerResults.html
          24_homer_motif_enrichment / ... / knownResults.html

For De novo motifs, what do I need to add in the above command?

Thank you in advance.

**Comment by JSuryatenggara** [comment]
Hi,

to be able to help you out more specifically, I will need to see how your input and output files look like. Do you mind sending them to my email: j.suryatenggara'at'u.nus.edu? Meanwhile, based on my initial suspicion, the missing annotation is probably caused by something wrong during the installation that homer is not correctly configured. You might want to try running this in the command line terminal: "perl [path_to_homer] / configureHomer.pl -install hg38". In my computer, the [path_to_homer] is home/anaconda3/share/homer/. After that, you can try running the annotation again with "bash 22_peaks_processing_script.sh" and see if configuring homer does the trick.

To have the homer motif enrichment files, you have to add a flag argument in the command line. Thanks for pointing out this issue, cause I did missed to update the command line optional arguments in the wiki. I updated it just now but to answer your question, it is: " --homer_motif [consensus / union / both]" added to your chipap.py command line, with [consensus / union / both] being the peak set(s) you want to run your motif search on. Another way to do it is to just run the .sh scripts in the folder 24_homer_motif_enrichment, since chipap actually generated those instructions even when we don't ask for it in the beginning when calling chipap.py . However, they are there and you can just run the process with simply entering into the command line "bash [path_to_script]".

Kindly let me know if you have more questions.

**Comment by mbassalbioinformatics** [comment]
Also, the output of chipap as its running is quite verbose, can you paste the terminal output here please?

**Comment by RM83** [comment]
I emailed you the terminal output and updates about the annotation and motif search part. Thank you so much for your prompt reply and your willingness to help.

**Comment by RM83** [comment]
The tool is running very well. I have no more issues. Thank you so much for all your help. ..:)
