### ISSUE TITLE
[BUG] GEM settings

### ISSUE THREAD

**Issue by nandobonf** [mbassalbioinformatics/ChIP-AP#3]
Thanks for massive work to put together all this code.
I found a bug in the GEM scripts, it actually does not take the "--thread" from the input.

This is my command:
`chipap.py \
--mode single \
--peak narrow \
--chipR1 /srv/ngs/analysis/nando/chipseq.test/SRR502538.fastq \
--ctrlR1 /srv/ngs/analysis/nando/chipseq.test/SRR502027.fastq \
--genome /srv/ngs/analysis/nando/references/Homo_sapiens/chipap/genomes/ \
--output SHSY5Y_GATA3 \
--setname SHSY5Y_GATA3 \
--ref hg19 \
--thread 16`

However in the GEM script I find the flag "--t 8.0" which outputs a java error:

`java -jar /srv/ngs/analysis/nando/anaconda3/envs/chipap/share/java/gem-2.7-0/gem.jar -Xmx10G --k_min 8 --k_max 12 --t 8.0 --d /srv/ngs/analysis/nando/references/Homo_sapiens/chipap/genomes/GEM/Read_Distribution_default.txt --g /srv/ngs/analysis/nando/references/Homo_sapiens/chipap/genomes/GEM/hg19.chrom.sizes --genome /srv/ngs/analysis/nando/references/Homo_sapiens/chipap/genomes/GEM/hg19_Chr_FASTA --s 2864785220 --expt /srv/ngs/analysis/nando/chipseq.test/SHSY5Y_GATA3/SHSY5Y_GATA3/08_results/SHSY5Y_GATA3_chip_rep1.bam --ctrl /srv/ngs/analysis/nando/chipseq.test/SHSY5Y_GATA3/SHSY5Y_GATA3/08_results/SHSY5Y_GATA3_ctrl_rep1.bam --f SAM --out /srv/ngs/analysis/nando/chipseq.test/SHSY5Y_GATA3/SHSY5Y_GATA3/12_gem_peak_calling/SHSY5Y_GATA3_GEM
`

Another (minor) bug is that the master script looks for a "default_settings_table.tsv" while in the genome compressed archive the file is named "default_settings_table.tsv"

Hope this helps.
Thanks!

**Comment by JSuryatenggara** [comment]
Hi Nando,

Thanks a lot for your report. It is very useful and we really appreciate it!

The first issue is that GEM was given a float value (8.0) instead of an integer (8) as flag argument for number of threads (-t). I fixed this in the main script chipap.py, so I believe that java error should not happen anymore with the latest release. However, I did set GEM to run with only half of the number you give in --thread (just like I did with bwa mem). The reason is that these two programs read and search the genome reference file and thus use a lot more memory compared to the other programs. When ChIP-AP is run without --thread specified, some computers may likely run out of memory.

I believe you meant it is named default_settings_table.txt in the genome compressed archive. Basically the same file, so that was a file naming error by me. It is fixed aand reuploaded. Now the one in the archive also has .tsv extension.

Thank you so much! Feel free to let me know if you have any more comment.

**Comment by nandobonf** [comment]
Hi, I'm glad it helped!
Another small bug is in the the file "GEM_IDR_input.narrowPeak". Here there are commas as decimal separators and this file cant be processed as it is. I changed the "," to "." and it works well. Hope you can reproduce it.

`>head -1 GEM_IDR_input.narrowPeak`
`chrY    13936396        13936446        chrY:13936396-13936446  0       .       9999,9  -1      -1      -1`

**Comment by JSuryatenggara** [comment]
Hi,
sorry, for this one, we couldn't reproduce your result. We just tried rerunning the script and in our result it is a period instead of a comma, just like it has always been. Perhaps there is a pre-installed software in your local system with different version than what is used in ChIP-AP, that somehow has a comma as the default decimal separator?

Thanks for the report, though. We will keep it in mind in case similar thing happens quite frequently.
